name: My-First-Workflow

on:
   workflow_dispatch:
     inputs:
       infra_env:
          description: 'Environment Name("prod" or "nonprod")'
          required: true
  

# env:
#   greet: "first time"

jobs:
  # tfdestroy:
  #   name: 'Terraform Destroy'
  #   runs-on: ubuntu-latest
    run-github-actions-job1:
        name: 'server-name'
        runs-on: ubuntu-latest
        steps:
         - name: 'Checkout'
           uses: actions/checkout@v1
         - name: 'first-step'
           if: ${{ github.event.inputs.infra_env == 'nonprod' }}
           run: echo "hello-world"
        
         - name: 'second-step'
           if: ${{ github.event.inputs.infra_env == 'prod' }}
           run: echo "iam learning github-actions"
