name: My-First-Workflow

on:
   workflow_dispatch:
     inputs:
       infra_env:
          description: 'Environment Name("prod" or "nonprod")'
          required: true
  

# env:
#   greet: "first time"

jobs:
  # tfdestroy:
  #   name: 'Terraform Destroy'
  #   runs-on: ubuntu-latest
    run-github-actions-job1:
        name: 'server-name'
        runs-on: ubuntu-latest
        steps:
         - name: 'Checkout'
           uses: actions/checkout@v1
         - name: 'first-step'
           if: ${{ github.event.inputs.infra_env == 'nonprod' }}
           run: eho "hello-world"
        
         - name: 'second-step'
           if: ${{ github.event.inputs.infra_env == 'prod' }}
           run: echo "iam learning github-actions"
   
         - name: Get Previous Pipeline Status
           id: get_status
           run: |
             # Fetch the last completed run of the same workflow
             PREVIOUS_RUN=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs?event=workflow_dispatch" | jq '.workflow_runs[1]')
             # Get the conclusion (status) of the previous run
             PREVIOUS_STATUS=$(echo "$PREVIOUS_RUN" | jq -r '.conclusion')

             echo "Previous Status: $PREVIOUS_STATUS"
