name: My-First-Workflow

on:
  workflow_dispatch:
    inputs:
      infra_select:
        description: 'prod or non-prod'
        required: true

env:
  greet: "first time"

jobs:  
  run-github-actions-job1:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        if: ${{github.event.inputs=="nonprod"}}
        run: echo "hello-world"
      - name: second-step
        if: ${{github.event.inputs=="prod"}}
        run: echo "iam learning github-actions $greet"
